# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 70%
        threshold: 5%
    patch:
      default:
        target: 50%
        threshold: 10%
        # 문서 파일 변경은 커버리지 체크 제외
        only_pulls: true

ignore:
  - "tests/**/*"
  - "**/__pycache__/**"
  - "**/conftest.py"
  - "docs/**/*"
  - "*.md"
  - "scripts/**/*"
  - "workflows/**/*"
  - "monitoring/**/*"
  - "db/**/*"
  - "deploy/**/*"

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true
